### ISSUE TITLE
別PCから操作したい

### ISSUE THREAD

**Issue by weiqiyang** [agent-system/lecture2019#25]
デスクトップ環境で動いているchoroenoid内のロボットをノートPCから操作したいが、rostopicが取得できない。

現状ではデスクトップで
```
Terminal1: 
$ roscore

Terminal2:
$ ./run.sh roslaunch **(略)
```
をしてchoreonoidを起動し、ノートPCで`rossetmaster`と`rossetip`を設定する。

そうするとノートPCから`rostopic list`と`rosparam get`はできるが、
`rostopic echo`が正常に作動しなく、以下のメッセージが表示さらる：
```
$ rostopic echo /tf
WARNING: no messages received and simulated time is active.
Is /clock being published?
```

また、デスクトップ側では`rostopic hz /tf`は270Hz、`rostopic hz /clock`は150Hz；
ノートPCからpublishされたtopicもデスクトップから`rostopic echo`で取得できる。

**Comment by YoheiKakiuchi** [comment]
DOCKER_ROS_IP 環境変数 が渡されて、それがdocker内のROS_IPに設定されているはずです。
なので、
~~~
DOCKER_ROS_IP={your_IP_address} ./run.sh
~~~
としてみると、どうなるでしょうか？

https://github.com/YoheiKakiuchi/robotsimulation-docker/blob/master/choreonoid_docker/run.sh#L18-L23
https://github.com/YoheiKakiuchi/robotsimulation-docker/blob/master/choreonoid_docker/my_entryrc#L8-L16

**Comment by weiqiyang** [comment]
なるほど、この設定で出来ました。ありがとうございます。
