### ISSUE TITLE
hsi_outputがパブリッシュされない

### ISSUE THREAD

**Issue by 326-T** [agent-system/lecture2019#27]
<pre>roslaunch jsk_pcl_ros hsi_color_filter.launch　INPUT:=AizuSpiderAA/ARM_CAMERA/points</pre>
をしてから
<pre>rosrun rviz rviz -d $(aizuspider_descriptn)/AizuSpiderAA.rviz</pre>
をしてrvizを開いても何も表示されないです。hsi_outputを見ても何もパブリッシュされていないようです。
<pre>rostopic echo /HSI_color_filter/hsi_output 
WARNING: no messages received and simulated time is active.
Is /clock being published?</pre>

**Comment by YoheiKakiuchi** [comment]
https://github.com/agent-system/lecture2019/issues/20
これと同じ問題ではないでしょうか

**Comment by 326-T** [comment]
ありがとうございます。
hsi_color_filter.launchはどのディレクトリにあるのでしょうか？
cdやroscdで一通り探したのですが見つけられませんでした。

**Comment by YoheiKakiuchi** [comment]
以下にあると思います
```
roscd jsk_pcl_ros
launch/hsi_color_filter.launch
```

**Comment by 326-T** [comment]
ありがとうございます。
euclidean_clusteringのノードをコメントアウトしたり
[https://github.com/agent-system/lecture2019/issues/22](url)
を参考にhsi_outputのノードのみにしたりしたのですが変わらなかったです。
以下が実行時の様子です。

<pre># roslaunch jsk_pcl_ros hsi_color_filter.launch INPUT:=AizuSpiderAA/ARM_CAMERA/points
... logging to /root/.ros/log/6ea42356-a25e-11e9-a012-f06e0bc15bfc/roslaunch-takeda-Surface-Book-2-2750.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is &lt;1GB.

<b>started roslaunch server http://localhost:36381/</b>

SUMMARY
========

PARAMETERS
 * /HSI_color_filter/hsi_filter/h_limit_max: 127
 * /HSI_color_filter/hsi_filter/h_limit_min: -128
 * /HSI_color_filter/hsi_filter/i_limit_max: 255
 * /HSI_color_filter/hsi_filter/i_limit_min: 0
 * /HSI_color_filter/hsi_filter/keep_organized: True
 * /HSI_color_filter/hsi_filter/s_limit_max: 255
 * /HSI_color_filter/hsi_filter/s_limit_min: 0
 * /HSI_color_filter/hsi_filter/use_indices: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /HSI_color_filter/
    hsi_filter (nodelet/nodelet)
    hsi_filter_manager (nodelet/nodelet)

<b>ROS_MASTER_URI=http://localhost:11311</b>

<b>process[HSI_color_filter/hsi_filter_manager-1]: started with pid [2767]</b>
[ INFO] [1562687456.004311890]: Initializing nodelet with 8 worker threads.
<b>process[HSI_color_filter/hsi_filter-2]: started with pid [2768]</b>
[ INFO] [1562687456.255441510]: Loading nodelet /HSI_color_filter/hsi_filter of type jsk_pcl/HSIColorFilter to manager hsi_filter_manager with the following remappings:
[ INFO] [1562687456.255514018]: /HSI_color_filter/hsi_filter/input -&gt; /HSI_color_filter/AizuSpiderAA/ARM_CAMERA/points
[ INFO] [1562687456.255545570]: /HSI_color_filter/hsi_filter/output -&gt; /HSI_color_filter/hsi_output
<font color="#C4A000">[ WARN] [1562687461.476071612, 1008.090999983]: &apos;/HSI_color_filter/hsi_filter&apos; subscribes topics only with child subscribers.</font>

</pre>

**Comment by 326-T** [comment]
hsi_color_filterの値は出るようになりました。
rvizで表示するためには何をaddすればよいのでしょうか？

**Comment by YoheiKakiuchi** [comment]
http://wiki.ros.org/rviz/UserGuide

4.1 Adding a new display

を参考にして、

- rviz Add ボタンを押す
- (by topic) を選択
- HSI_color_filter/hsi_output トピックを選ぶ

として、フィルタ結果の点群がでるかと思います

**Comment by 326-T** [comment]
解決いたしました。
ありがとうございます。
./exec.sh
$ rosrun rviz rviz -d $(aizuspider_description)/AizuSpiderAA.rviz
を
./exec.sh
$ roscd aizuspider_description
$ rosrun rviz rviz -d AizuSpiderAA.rviz
としたところ解決いたしました。
