### ISSUE TITLE
課題の詳細が知りたい

### ISSUE THREAD

**Issue by MiraiHattori** [agent-system/lecture2019#30]
昨日機械系事務室前の掲示板を見に行ったところ，タイミングの問題か掲示がなかったので質問させていただきます．

授業でスライドとして示された課題はA4両面印刷で機械系事務室に提出することになっていると思うのですが，
agent-system/lecture2019 のREADME.mdに書いてある課題はどのように扱われるものなのでしょうか？

よろしくお願いします．

**Comment by YoheiKakiuchi** [comment]
遅くなりました、事務室前に掲示されています。

**Comment by MiraiHattori** [comment]
ありがとうございます．
