### ISSUE TITLE
IMUのTFが存在しない

### ISSUE THREAD

**Issue by EndoYuuki** [agent-system/lecture2019#31]
IMUを使ってDead Reckoningをしようと思っているのですが，IMUのTF（AizuSpiderAA/CHASSIS_ACCELERATION_SENSOR，AizuSpiderAA/CHASSIS_RATE_GYRO_SENSOR)が見つかりません．
提供されていないのであれば他の方法にしようと思うのですが，もし用意されているのであればその起動方法を教えていただきたいです．

**Comment by YoheiKakiuchi** [comment]
現状では出ていないのですが、
CHASSISと同じ位置であり、AizuSpiderSS.urdfの最後(</robot> の直前)に
https://github.com/agent-system/aizuspider_description/blob/master/AizuSpiderSS.urdf

以下を追加すると出るかと思います。
~~~
  <joint name="CHASSIS_ACCELERATION_SENSOR_tf" type="fixed">
    <parent link="CHASSIS"/>
    <child  link="CHASSIS_ACCELERATION_SENSOR"/>
  </joint>
  <joint name="CHASSIS_RATE_GYRO_SENSOR_tf" type="fixed">
    <parent link="CHASSIS"/>
    <child  link="CHASSIS_RATE_GYRO_SENSOR"/>
  </joint>
~~~

または、launch立ち上げ後に以下を実行しておくのでも良いかと思います。
~~~
rosrun static_transform_publisher 0 0 0 0 0 0 AizuSpiderAA/CHASSIS AizuSpiderAA/CHASSIS_ACCELERATION_SENSOR 50
rosrun static_transform_publisher 0 0 0 0 0 0 AizuSpiderAA/CHASSIS AizuSpiderAA/CHASSIS_RATE_GYRO_SENSOR 50
~~~

**Comment by EndoYuuki** [comment]
ありがとうございます．教えていただいた方法で解決することができました．
