### ISSUE TITLE
./run.shが実行できない

### ISSUE THREAD

**Issue by TK-19** [agent-system/lecture2019#6]
./run.shを実行しようとすると以下のようなエラーが発生します。
GPU：Radeon
Ubuntu: 18.04
Docker version 18.09.6
です。
何卒宜しくお願いいたします。

$ ./run.sh
localuser:root being added to access control list
choreonoidsim
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
$ DOCKER=docker ./run.sh
localuser:root being added to access control list
Error: No such container: choreonoidsim
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'

なお、
$ docker images
REPOSITORY                    TAG                       IMAGE ID            CREATED             SIZE
yoheikakiuchi/choreonoidsim   16.04_no_gl_release-1.7   4b818e0fbb17        41 hours ago        6.57GB
osrf/ros                      kinetic-desktop           d187eed8951a        46 hours ago        2.32GB
osrf/ros                      melodic-desktop           ba5a94872b4b        2 days ago          2.1GB
yoheikakiuchi/choreonoid      16.04_no_gl_release-1.7   fb0da50ddeca        8 days ago          4.2GB
yoheikakiuchi/choreonoidsim   16.04_release-1.7         27b22fd7ce50        2 weeks ago         6.34GB
bash                          latest                    417531d957ab        3 weeks ago         15.2MB
yoheikakiuchi/choreonoid      16.04_no_gl_latest_ros    56153cd9808b        6 weeks ago         3.9GB
yoheikakiuchi/choreonoidsim   16.04_no_gl_release-1.6   89d54472cbee        6 weeks ago         6.49GB
yoheikakiuchi/choreonoid      16.04_latest_ros          060e0f082b63        6 weeks ago         3.64GB
yoheikakiuchi/choreonoidsim   16.04_release-1.6         81cb0a1afb94        6 weeks ago         6.33GB
ubuntu                        xenial                    9361ce633ff1        2 months ago        118MB
ubuntu                        bionic                    94e814e2efa8        2 months ago        88.9MB
hello-world                   latest                    fce289e99eb9        5 months ago        1.84kB

$ docker ps -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS               NAMES
c3727daf5726        yoheikakiuchi/choreonoidsim:16.04_no_gl_release-1.7   "/my_entrypoint.sh b…"   31 minutes ago      Exited (0) 23 minutes ago                       frosty_keller
21e08707075f        yoheikakiuchi/choreonoid:16.04_no_gl_release-1.7      "/my_entrypoint.sh b…"   40 minutes ago      Exited (0) 36 minutes ago                       admiring_mendel
cfc3dcb5aa30        yoheikakiuchi/choreonoidsim:16.04_no_gl_release-1.6   "/my_entrypoint.sh b…"   44 hours ago        Exited (0) 44 hours ago                         friendly_dhawan
cc7bb18078a6        yoheikakiuchi/choreonoidsim:16.04_no_gl_release-1.6   "/my_entrypoint.sh b…"   44 hours ago        Exited (0) 44 hours ago                         festive_chebyshev
024fcbe53a3d        yoheikakiuchi/choreonoidsim:16.04_no_gl_release-1.6   "/my_entrypoint.sh b…"   44 hours ago        Exited (0) 44 hours ago                         silly_dirac
ac964bf06765        osrf/ros:kinetic-desktop                              "/ros_entrypoint.sh …"   44 hours ago        Exited (1) 44 hours ago                         cranky_wu
c4df03e36dea        osrf/ros:melodic-desktop                              "/ros_entrypoint.sh …"   44 hours ago        Exited (1) 44 hours ago                         flamboyant_heyrovsky
df5aa032ab4a        osrf/ros:melodic-desktop                              "/ros_entrypoint.sh …"   44 hours ago        Exited (0) 44 hours ago                         wonderful_mcclintock
b39ca914df95        osrf/ros:kinetic-desktop                              "/ros_entrypoint.sh …"   44 hours ago        Exited (0) 44 hours ago                         angry_heyrovsky
0d70d7d0bf50        osrf/ros:kinetic-desktop                              "/ros_entrypoint.sh …"   44 hours ago        Exited (130) 44 hours ago                       test_container
3c0d2960402d        hello-world                                           "/hello"                 11 days ago         Exited (0) 11 days ago                          nifty_lichterman
c38aaa07484d        yoheikakiuchi/choreonoid:16.04_no_gl_latest_ros       "/my_entrypoint.sh b…"   6 weeks ago         Exited (127) 6 weeks ago                        hardcore_shirley
2e964dcca1dc        ubuntu:bionic                                         "bash"                   6 weeks ago         Exited (127) 6 weeks ago                        relaxed_varahamihira
32610c4c007d        ubuntu:xenial                                         "bash"                   6 weeks ago         Exited (0) 6 weeks ago                          naughty_jones
c645f4a8dee9        hello-world                                           "/hello"                 6 weeks ago         Exited (0) 6 weeks ago                          nifty_dirac

です。

**Comment by YoheiKakiuchi** [comment]
nvidia以外のグラフィックボードの場合は、run_no_gl.sh を試してもらえますでしょうか。

**Comment by TK-19** [comment]
実行できました。ありがとうございます！
