### ISSUE TITLE
Aizu Spiderのアームが操作できない

### ISSUE THREAD

**Issue by EndoYuuki** [agent-system/lecture2019#7]
コントローラを持っていないため，Aizu Spiderを動作させる際に， 
https://choreonoid.org/ja/manuals/latest/wrs2018/sample-controllers.html#id7
を参考に，ボタンをエミュレートして操作を試みたのですがアームが動作しません．

一度PSボタン（ros トピックで言うとbuttons[10]=1）を押してアームの動作モードになっているはずなのですが，アームがいずれとも動作する気配がありません．

クローラは動作することを確認
また実際にpublishされているメッセージ上をrostopic echoで確認し、対応する操作の信号が出ていることは確認しています．

ボタンの操作方法や，何か間違っていることなどありましたらご教授いただけると幸いです．

**Comment by EndoYuuki** [comment]
環境は以下のとおりです。
- Ubuntu 16.04.6 LTS 64 ビット
- Docker version 18.09.6, build 481bc77
no_glで動作させています。

**Comment by YoheiKakiuchi** [comment]
以下の説明を試して見て下さい
~~~
初期設定ではジョイスティックで移動しかできなくなっています。 振り付け等で関節を動かしてください。

以下で、全身のジョイスティック動作ができるようになります。（もう一回すると戻ります、相互に行き来するのはあまりうまく行きません）

./exec.sh rosrun aizuspider_description toggle_trajectory_controll.py -N AizuSpiderAA
~~~

**Comment by EndoYuuki** [comment]
その操作を失念していました．
ありがとうございます．無事動作しました
