### ISSUE TITLE
Choreonoid上でJAXON搭載のmultisenseの使い方がわからない

### ISSUE THREAD

**Issue by MiraiHattori** [agent-system/lecture2019#9]
choreonoid上でJAXON頭部のmultisenseから得られるorganized rgb pointcloud2(?)を用いて平面認識を行いたいのですが，どのように行えばできるでしょうか．

/multisense_local/organized_image_points2はrvizで表示されるので，自分で平面認識ノードを書けば見られるのですが，すでに認識ノードが用意されているならばそちらを使いたいと思っております．

以下わからないなりに自分が試したことになります．
jsk_pcl_rosを用いて平面認識が行えると思ったので以下のようにしました．
choreonoidが立ち上がっているのとは別ターミナルでexec.shを実行し，
roslaunch jsk_pcl_ros laser_multi_plane_detection.launch JOINT_STATES:=/multisense_local/joint_states BASE_FRAME_ID:=left_camera_optical_frame
として，さらに別ターミナルでrvizを立ち上げてPointCloud2を追加し見てみたのですが，/tilt_multi_plane_detection以下には何も表示されなかった

**Comment by YoheiKakiuchi** [comment]
choreonoidのmultisenseは実際のものと違っている部分があって、
/multisense_local/organized_image_points2_colorなどはその一部です。
このトピックは実際のmulitsenseにはついていないdepthカメラから出てくる点群です。
（choreonoidの頭部左カメラはdepth cameraになっている）

laser_multi_plane_detectionはlaserの点群でplaneを見つけるものです。
（それも確かに動いてもいいのですが。。。）

現実的には、/multisense_local/organized_image_points2_color をinputとして以下を使ってもらえればできるかと思います。
https://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_pcl_ros/nodes/organized_multi_plane_segmentation.html

だいぶ古いけど、このlaunchが参考になるかも
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/launch/footstep_recognition.launch

**Comment by MiraiHattori** [comment]
```xml
<launch>
 <node pkg="nodelet" type="nodelet" name="multi_plane_estimate"
        args="standalone jsk_pcl/OrganizedMultiPlaneSegmentation"
        clear_params="false">
    <remap from="~input" to="/multisense_local/organized_image_points2_color"/>
    <rosparam>
      max_curvature: 0.01
      estimate_normal: true
      min_size: 100
    </rosparam>
  </node>
</launch>
```

これをplane.launchとして roslaunch plane.launchした上で，rvizのaddからPolygonArrayを選択することで平面の多角形を見ることができました．ありがとうございます．
